// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: proto/secretKey/secretKey.proto

package secretKey

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

import (
	context "context"
	client "github.com/micro/go-micro/v2/client"
	server "github.com/micro/go-micro/v2/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ client.Option
var _ server.Option

// Client API for SecretKeys service

type SecretKeysService interface {
	// 权限验证授权
	// 全部权限
	All(ctx context.Context, in *Request, opts ...client.CallOption) (*Response, error)
	// 获取权限列表
	List(ctx context.Context, in *Request, opts ...client.CallOption) (*Response, error)
	// 根据 唯一 获取权限
	Get(ctx context.Context, in *Request, opts ...client.CallOption) (*Response, error)
	// 创建权限
	Create(ctx context.Context, in *Request, opts ...client.CallOption) (*Response, error)
	// 更新权限
	Update(ctx context.Context, in *Request, opts ...client.CallOption) (*Response, error)
	// 删除权限
	Delete(ctx context.Context, in *Request, opts ...client.CallOption) (*Response, error)
}

type secretKeysService struct {
	c    client.Client
	name string
}

func NewSecretKeysService(name string, c client.Client) SecretKeysService {
	return &secretKeysService{
		c:    c,
		name: name,
	}
}

func (c *secretKeysService) All(ctx context.Context, in *Request, opts ...client.CallOption) (*Response, error) {
	req := c.c.NewRequest(c.name, "SecretKeys.All", in)
	out := new(Response)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *secretKeysService) List(ctx context.Context, in *Request, opts ...client.CallOption) (*Response, error) {
	req := c.c.NewRequest(c.name, "SecretKeys.List", in)
	out := new(Response)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *secretKeysService) Get(ctx context.Context, in *Request, opts ...client.CallOption) (*Response, error) {
	req := c.c.NewRequest(c.name, "SecretKeys.Get", in)
	out := new(Response)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *secretKeysService) Create(ctx context.Context, in *Request, opts ...client.CallOption) (*Response, error) {
	req := c.c.NewRequest(c.name, "SecretKeys.Create", in)
	out := new(Response)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *secretKeysService) Update(ctx context.Context, in *Request, opts ...client.CallOption) (*Response, error) {
	req := c.c.NewRequest(c.name, "SecretKeys.Update", in)
	out := new(Response)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *secretKeysService) Delete(ctx context.Context, in *Request, opts ...client.CallOption) (*Response, error) {
	req := c.c.NewRequest(c.name, "SecretKeys.Delete", in)
	out := new(Response)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for SecretKeys service

type SecretKeysHandler interface {
	// 权限验证授权
	// 全部权限
	All(context.Context, *Request, *Response) error
	// 获取权限列表
	List(context.Context, *Request, *Response) error
	// 根据 唯一 获取权限
	Get(context.Context, *Request, *Response) error
	// 创建权限
	Create(context.Context, *Request, *Response) error
	// 更新权限
	Update(context.Context, *Request, *Response) error
	// 删除权限
	Delete(context.Context, *Request, *Response) error
}

func RegisterSecretKeysHandler(s server.Server, hdlr SecretKeysHandler, opts ...server.HandlerOption) error {
	type secretKeys interface {
		All(ctx context.Context, in *Request, out *Response) error
		List(ctx context.Context, in *Request, out *Response) error
		Get(ctx context.Context, in *Request, out *Response) error
		Create(ctx context.Context, in *Request, out *Response) error
		Update(ctx context.Context, in *Request, out *Response) error
		Delete(ctx context.Context, in *Request, out *Response) error
	}
	type SecretKeys struct {
		secretKeys
	}
	h := &secretKeysHandler{hdlr}
	return s.Handle(s.NewHandler(&SecretKeys{h}, opts...))
}

type secretKeysHandler struct {
	SecretKeysHandler
}

func (h *secretKeysHandler) All(ctx context.Context, in *Request, out *Response) error {
	return h.SecretKeysHandler.All(ctx, in, out)
}

func (h *secretKeysHandler) List(ctx context.Context, in *Request, out *Response) error {
	return h.SecretKeysHandler.List(ctx, in, out)
}

func (h *secretKeysHandler) Get(ctx context.Context, in *Request, out *Response) error {
	return h.SecretKeysHandler.Get(ctx, in, out)
}

func (h *secretKeysHandler) Create(ctx context.Context, in *Request, out *Response) error {
	return h.SecretKeysHandler.Create(ctx, in, out)
}

func (h *secretKeysHandler) Update(ctx context.Context, in *Request, out *Response) error {
	return h.SecretKeysHandler.Update(ctx, in, out)
}

func (h *secretKeysHandler) Delete(ctx context.Context, in *Request, out *Response) error {
	return h.SecretKeysHandler.Delete(ctx, in, out)
}
